// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChatKind.
const (
	ChatKindChannel ChatKind = "channel"
	ChatKindDirect  ChatKind = "direct"
	ChatKindGroup   ChatKind = "group"
)

// Valid indicates whether the value is a known member of the ChatKind enum.
func (e ChatKind) Valid() bool {
	switch e {
	case ChatKindChannel:
		return true
	case ChatKindDirect:
		return true
	case ChatKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for ChatRole.
const (
	ChatRoleAdmin  ChatRole = "admin"
	ChatRoleMember ChatRole = "member"
	ChatRoleOwner  ChatRole = "owner"
)

// Valid indicates whether the value is a known member of the ChatRole enum.
func (e ChatRole) Valid() bool {
	switch e {
	case ChatRoleAdmin:
		return true
	case ChatRoleMember:
		return true
	case ChatRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for ChatVisibility.
const (
	ChatVisibilityPrivate ChatVisibility = "private"
	ChatVisibilityPublic  ChatVisibility = "public"
)

// Valid indicates whether the value is a known member of the ChatVisibility enum.
func (e ChatVisibility) Valid() bool {
	switch e {
	case ChatVisibilityPrivate:
		return true
	case ChatVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatRequestKind.
const (
	CreateChatRequestKindChannel CreateChatRequestKind = "channel"
	CreateChatRequestKindDirect  CreateChatRequestKind = "direct"
	CreateChatRequestKindGroup   CreateChatRequestKind = "group"
)

// Valid indicates whether the value is a known member of the CreateChatRequestKind enum.
func (e CreateChatRequestKind) Valid() bool {
	switch e {
	case CreateChatRequestKindChannel:
		return true
	case CreateChatRequestKindDirect:
		return true
	case CreateChatRequestKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatRequestVisibility.
const (
	CreateChatRequestVisibilityPrivate CreateChatRequestVisibility = "private"
	CreateChatRequestVisibilityPublic  CreateChatRequestVisibility = "public"
)

// Valid indicates whether the value is a known member of the CreateChatRequestVisibility enum.
func (e CreateChatRequestVisibility) Valid() bool {
	switch e {
	case CreateChatRequestVisibilityPrivate:
		return true
	case CreateChatRequestVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for CreateInvitationRequestRole.
const (
	CreateInvitationRequestRoleAdmin  CreateInvitationRequestRole = "admin"
	CreateInvitationRequestRoleMember CreateInvitationRequestRole = "member"
)

// Valid indicates whether the value is a known member of the CreateInvitationRequestRole enum.
func (e CreateInvitationRequestRole) Valid() bool {
	switch e {
	case CreateInvitationRequestRoleAdmin:
		return true
	case CreateInvitationRequestRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for InvitationRole.
const (
	InvitationRoleAdmin  InvitationRole = "admin"
	InvitationRoleMember InvitationRole = "member"
)

// Valid indicates whether the value is a known member of the InvitationRole enum.
func (e InvitationRole) Valid() bool {
	switch e {
	case InvitationRoleAdmin:
		return true
	case InvitationRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleOwner  UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleMember:
		return true
	case UserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active      UserStatus = "active"
	Deactivated UserStatus = "deactivated"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Deactivated:
		return true
	default:
		return false
	}
}

// AcceptInvitationRequest defines model for AcceptInvitationRequest.
type AcceptInvitationRequest struct {
	DisplayName string  `json:"display_name"`
	Handle      string  `json:"handle"`
	Password    string  `json:"password"`
	Timezone    *string `json:"timezone,omitempty"`
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	DisplayName      string              `json:"display_name"`
	Email            openapi_types.Email `json:"email"`
	Handle           string              `json:"handle"`
	OrganizationName string              `json:"organization_name"`
	OrganizationSlug string              `json:"organization_slug"`
	Password         string              `json:"password"`
	Timezone         *string             `json:"timezone,omitempty"`
}

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	Bootstrapped bool `json:"bootstrapped"`
}

// Chat defines model for Chat.
type Chat struct {
	ArchivedAt *time.Time         `json:"archived_at,omitempty"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Kind       ChatKind           `json:"kind"`
	Name       *string            `json:"name,omitempty"`
	Role       ChatRole           `json:"role"`
	Topic      string             `json:"topic"`
	Visibility ChatVisibility     `json:"visibility"`
}

// ChatKind defines model for Chat.Kind.
type ChatKind string

// ChatRole defines model for Chat.Role.
type ChatRole string

// ChatVisibility defines model for Chat.Visibility.
type ChatVisibility string

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Kind       CreateChatRequestKind        `json:"kind"`
	MemberIds  *[]openapi_types.UUID        `json:"member_ids,omitempty"`
	Name       *string                      `json:"name,omitempty"`
	Topic      *string                      `json:"topic,omitempty"`
	Visibility *CreateChatRequestVisibility `json:"visibility,omitempty"`
}

// CreateChatRequestKind defines model for CreateChatRequest.Kind.
type CreateChatRequestKind string

// CreateChatRequestVisibility defines model for CreateChatRequest.Visibility.
type CreateChatRequestVisibility string

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	Email openapi_types.Email          `json:"email"`
	Role  *CreateInvitationRequestRole `json:"role,omitempty"`
}

// CreateInvitationRequestRole defines model for CreateInvitationRequest.Role.
type CreateInvitationRequestRole string

// Error defines model for Error.
type Error struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"request_id"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	AcceptUrl *string             `json:"accept_url,omitempty"`
	Email     openapi_types.Email `json:"email"`
	ExpiresAt time.Time           `json:"expires_at"`
	Id        openapi_types.UUID  `json:"id"`
	Role      InvitationRole      `json:"role"`
}

// InvitationRole defines model for Invitation.Role.
type InvitationRole string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt  time.Time          `json:"created_at"`
	Current    bool               `json:"current"`
	ExpiresAt  time.Time          `json:"expires_at"`
	Id         openapi_types.UUID `json:"id"`
	IpAddress  *string            `json:"ip_address,omitempty"`
	LastSeenAt time.Time          `json:"last_seen_at"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
	UserAgent  string             `json:"user_agent"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessExpiresAt time.Time `json:"access_expires_at"`
	AccessToken     string    `json:"access_token"`
	User            User      `json:"user"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Handle      *string `json:"handle,omitempty"`
	Timezone    *string `json:"timezone,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Handle      string              `json:"handle"`
	Id          openapi_types.UUID  `json:"id"`
	OrgId       openapi_types.UUID  `json:"org_id"`
	Role        UserRole            `json:"role"`
	Status      UserStatus          `json:"status"`
	Timezone    string              `json:"timezone"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserStatus defines model for User.Status.
type UserStatus string

// Tokens defines model for Tokens.
type Tokens = TokenResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// BootstrapJSONRequestBody defines body for Bootstrap for application/json ContentType.
type BootstrapJSONRequestBody = BootstrapRequest

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = CreateInvitationRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = AcceptInvitationRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest
