// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActorSummaryType.
const (
	ActorSummaryTypeAgent ActorSummaryType = "agent"
	ActorSummaryTypeUser  ActorSummaryType = "user"
)

// Valid indicates whether the value is a known member of the ActorSummaryType enum.
func (e ActorSummaryType) Valid() bool {
	switch e {
	case ActorSummaryTypeAgent:
		return true
	case ActorSummaryTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for AddChatMemberRequestRole.
const (
	AddChatMemberRequestRoleAdmin  AddChatMemberRequestRole = "admin"
	AddChatMemberRequestRoleMember AddChatMemberRequestRole = "member"
	AddChatMemberRequestRoleOwner  AddChatMemberRequestRole = "owner"
)

// Valid indicates whether the value is a known member of the AddChatMemberRequestRole enum.
func (e AddChatMemberRequestRole) Valid() bool {
	switch e {
	case AddChatMemberRequestRoleAdmin:
		return true
	case AddChatMemberRequestRoleMember:
		return true
	case AddChatMemberRequestRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for ChatKind.
const (
	ChatKindChannel ChatKind = "channel"
	ChatKindDirect  ChatKind = "direct"
	ChatKindGroup   ChatKind = "group"
)

// Valid indicates whether the value is a known member of the ChatKind enum.
func (e ChatKind) Valid() bool {
	switch e {
	case ChatKindChannel:
		return true
	case ChatKindDirect:
		return true
	case ChatKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for ChatNotifyLevel.
const (
	ChatNotifyLevelAll      ChatNotifyLevel = "all"
	ChatNotifyLevelMentions ChatNotifyLevel = "mentions"
	ChatNotifyLevelNone     ChatNotifyLevel = "none"
)

// Valid indicates whether the value is a known member of the ChatNotifyLevel enum.
func (e ChatNotifyLevel) Valid() bool {
	switch e {
	case ChatNotifyLevelAll:
		return true
	case ChatNotifyLevelMentions:
		return true
	case ChatNotifyLevelNone:
		return true
	default:
		return false
	}
}

// Defines values for ChatRole.
const (
	ChatRoleAdmin  ChatRole = "admin"
	ChatRoleMember ChatRole = "member"
	ChatRoleOwner  ChatRole = "owner"
)

// Valid indicates whether the value is a known member of the ChatRole enum.
func (e ChatRole) Valid() bool {
	switch e {
	case ChatRoleAdmin:
		return true
	case ChatRoleMember:
		return true
	case ChatRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for ChatVisibility.
const (
	ChatVisibilityPrivate ChatVisibility = "private"
	ChatVisibilityPublic  ChatVisibility = "public"
)

// Valid indicates whether the value is a known member of the ChatVisibility enum.
func (e ChatVisibility) Valid() bool {
	switch e {
	case ChatVisibilityPrivate:
		return true
	case ChatVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for ChatFolderColor.
const (
	Amber  ChatFolderColor = "amber"
	Blue   ChatFolderColor = "blue"
	Cyan   ChatFolderColor = "cyan"
	Green  ChatFolderColor = "green"
	Orange ChatFolderColor = "orange"
	Pink   ChatFolderColor = "pink"
	Red    ChatFolderColor = "red"
	Slate  ChatFolderColor = "slate"
	Teal   ChatFolderColor = "teal"
	Violet ChatFolderColor = "violet"
)

// Valid indicates whether the value is a known member of the ChatFolderColor enum.
func (e ChatFolderColor) Valid() bool {
	switch e {
	case Amber:
		return true
	case Blue:
		return true
	case Cyan:
		return true
	case Green:
		return true
	case Orange:
		return true
	case Pink:
		return true
	case Red:
		return true
	case Slate:
		return true
	case Teal:
		return true
	case Violet:
		return true
	default:
		return false
	}
}

// Defines values for ChatFolderIcon.
const (
	Book        ChatFolderIcon = "book"
	Bookmark    ChatFolderIcon = "bookmark"
	Bot         ChatFolderIcon = "bot"
	Briefcase   ChatFolderIcon = "briefcase"
	Calendar    ChatFolderIcon = "calendar"
	Camera      ChatFolderIcon = "camera"
	Car         ChatFolderIcon = "car"
	Cat         ChatFolderIcon = "cat"
	Chart       ChatFolderIcon = "chart"
	Check       ChatFolderIcon = "check"
	Clock       ChatFolderIcon = "clock"
	Cloud       ChatFolderIcon = "cloud"
	Code        ChatFolderIcon = "code"
	Coffee      ChatFolderIcon = "coffee"
	Database    ChatFolderIcon = "database"
	Dog         ChatFolderIcon = "dog"
	Dumbbell    ChatFolderIcon = "dumbbell"
	Flame       ChatFolderIcon = "flame"
	Flower      ChatFolderIcon = "flower"
	Folder      ChatFolderIcon = "folder"
	Gamepad     ChatFolderIcon = "gamepad"
	Gift        ChatFolderIcon = "gift"
	Globe       ChatFolderIcon = "globe"
	Graduation  ChatFolderIcon = "graduation"
	Hash        ChatFolderIcon = "hash"
	Heart       ChatFolderIcon = "heart"
	Home        ChatFolderIcon = "home"
	Image       ChatFolderIcon = "image"
	Leaf        ChatFolderIcon = "leaf"
	Lightbulb   ChatFolderIcon = "lightbulb"
	Map         ChatFolderIcon = "map"
	Moon        ChatFolderIcon = "moon"
	Mountain    ChatFolderIcon = "mountain"
	Music       ChatFolderIcon = "music"
	Palette     ChatFolderIcon = "palette"
	Party       ChatFolderIcon = "party"
	Plane       ChatFolderIcon = "plane"
	Rocket      ChatFolderIcon = "rocket"
	ShoppingBag ChatFolderIcon = "shopping-bag"
	Smile       ChatFolderIcon = "smile"
	Star        ChatFolderIcon = "star"
	Sun         ChatFolderIcon = "sun"
	Target      ChatFolderIcon = "target"
	Terminal    ChatFolderIcon = "terminal"
	Trophy      ChatFolderIcon = "trophy"
	Umbrella    ChatFolderIcon = "umbrella"
	Users       ChatFolderIcon = "users"
	Wallet      ChatFolderIcon = "wallet"
	Waves       ChatFolderIcon = "waves"
	Zap         ChatFolderIcon = "zap"
)

// Valid indicates whether the value is a known member of the ChatFolderIcon enum.
func (e ChatFolderIcon) Valid() bool {
	switch e {
	case Book:
		return true
	case Bookmark:
		return true
	case Bot:
		return true
	case Briefcase:
		return true
	case Calendar:
		return true
	case Camera:
		return true
	case Car:
		return true
	case Cat:
		return true
	case Chart:
		return true
	case Check:
		return true
	case Clock:
		return true
	case Cloud:
		return true
	case Code:
		return true
	case Coffee:
		return true
	case Database:
		return true
	case Dog:
		return true
	case Dumbbell:
		return true
	case Flame:
		return true
	case Flower:
		return true
	case Folder:
		return true
	case Gamepad:
		return true
	case Gift:
		return true
	case Globe:
		return true
	case Graduation:
		return true
	case Hash:
		return true
	case Heart:
		return true
	case Home:
		return true
	case Image:
		return true
	case Leaf:
		return true
	case Lightbulb:
		return true
	case Map:
		return true
	case Moon:
		return true
	case Mountain:
		return true
	case Music:
		return true
	case Palette:
		return true
	case Party:
		return true
	case Plane:
		return true
	case Rocket:
		return true
	case ShoppingBag:
		return true
	case Smile:
		return true
	case Star:
		return true
	case Sun:
		return true
	case Target:
		return true
	case Terminal:
		return true
	case Trophy:
		return true
	case Umbrella:
		return true
	case Users:
		return true
	case Wallet:
		return true
	case Waves:
		return true
	case Zap:
		return true
	default:
		return false
	}
}

// Defines values for ChatMemberRole.
const (
	ChatMemberRoleAdmin  ChatMemberRole = "admin"
	ChatMemberRoleMember ChatMemberRole = "member"
	ChatMemberRoleOwner  ChatMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the ChatMemberRole enum.
func (e ChatMemberRole) Valid() bool {
	switch e {
	case ChatMemberRoleAdmin:
		return true
	case ChatMemberRoleMember:
		return true
	case ChatMemberRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for ChatNotificationPreferencesNotifyLevel.
const (
	ChatNotificationPreferencesNotifyLevelAll      ChatNotificationPreferencesNotifyLevel = "all"
	ChatNotificationPreferencesNotifyLevelMentions ChatNotificationPreferencesNotifyLevel = "mentions"
	ChatNotificationPreferencesNotifyLevelNone     ChatNotificationPreferencesNotifyLevel = "none"
)

// Valid indicates whether the value is a known member of the ChatNotificationPreferencesNotifyLevel enum.
func (e ChatNotificationPreferencesNotifyLevel) Valid() bool {
	switch e {
	case ChatNotificationPreferencesNotifyLevelAll:
		return true
	case ChatNotificationPreferencesNotifyLevelMentions:
		return true
	case ChatNotificationPreferencesNotifyLevelNone:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionTestRequestKind.
const (
	S3   ConnectionTestRequestKind = "s3"
	Smtp ConnectionTestRequestKind = "smtp"
)

// Valid indicates whether the value is a known member of the ConnectionTestRequestKind enum.
func (e ConnectionTestRequestKind) Valid() bool {
	switch e {
	case S3:
		return true
	case Smtp:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatRequestKind.
const (
	CreateChatRequestKindChannel CreateChatRequestKind = "channel"
	CreateChatRequestKindDirect  CreateChatRequestKind = "direct"
	CreateChatRequestKindGroup   CreateChatRequestKind = "group"
)

// Valid indicates whether the value is a known member of the CreateChatRequestKind enum.
func (e CreateChatRequestKind) Valid() bool {
	switch e {
	case CreateChatRequestKindChannel:
		return true
	case CreateChatRequestKindDirect:
		return true
	case CreateChatRequestKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatRequestVisibility.
const (
	CreateChatRequestVisibilityPrivate CreateChatRequestVisibility = "private"
	CreateChatRequestVisibilityPublic  CreateChatRequestVisibility = "public"
)

// Valid indicates whether the value is a known member of the CreateChatRequestVisibility enum.
func (e CreateChatRequestVisibility) Valid() bool {
	switch e {
	case CreateChatRequestVisibilityPrivate:
		return true
	case CreateChatRequestVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for CreateInvitationRequestRole.
const (
	CreateInvitationRequestRoleAdmin  CreateInvitationRequestRole = "admin"
	CreateInvitationRequestRoleMember CreateInvitationRequestRole = "member"
)

// Valid indicates whether the value is a known member of the CreateInvitationRequestRole enum.
func (e CreateInvitationRequestRole) Valid() bool {
	switch e {
	case CreateInvitationRequestRoleAdmin:
		return true
	case CreateInvitationRequestRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for CreateMessageRequestBodyFormat.
const (
	CreateMessageRequestBodyFormatMarkdown CreateMessageRequestBodyFormat = "markdown"
	CreateMessageRequestBodyFormatPlain    CreateMessageRequestBodyFormat = "plain"
)

// Valid indicates whether the value is a known member of the CreateMessageRequestBodyFormat enum.
func (e CreateMessageRequestBodyFormat) Valid() bool {
	switch e {
	case CreateMessageRequestBodyFormatMarkdown:
		return true
	case CreateMessageRequestBodyFormatPlain:
		return true
	default:
		return false
	}
}

// Defines values for DirectoryChatKind.
const (
	DirectoryChatKindChannel DirectoryChatKind = "channel"
	DirectoryChatKindGroup   DirectoryChatKind = "group"
)

// Valid indicates whether the value is a known member of the DirectoryChatKind enum.
func (e DirectoryChatKind) Valid() bool {
	switch e {
	case DirectoryChatKindChannel:
		return true
	case DirectoryChatKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for DraftBodyFormat.
const (
	DraftBodyFormatMarkdown DraftBodyFormat = "markdown"
	DraftBodyFormatPlain    DraftBodyFormat = "plain"
)

// Valid indicates whether the value is a known member of the DraftBodyFormat enum.
func (e DraftBodyFormat) Valid() bool {
	switch e {
	case DraftBodyFormatMarkdown:
		return true
	case DraftBodyFormatPlain:
		return true
	default:
		return false
	}
}

// Defines values for DurableEventTypeV1.
const (
	ActorStatusUpdated DurableEventTypeV1 = "actor.status.updated"
	ChatArchived       DurableEventTypeV1 = "chat.archived"
	ChatCreated        DurableEventTypeV1 = "chat.created"
	ChatUpdated        DurableEventTypeV1 = "chat.updated"
	DraftDeleted       DurableEventTypeV1 = "draft.deleted"
	DraftUpdated       DurableEventTypeV1 = "draft.updated"
	MemberJoined       DurableEventTypeV1 = "member.joined"
	MemberRemoved      DurableEventTypeV1 = "member.removed"
	MemberUpdated      DurableEventTypeV1 = "member.updated"
	MessageCreated     DurableEventTypeV1 = "message.created"
	MessageDeleted     DurableEventTypeV1 = "message.deleted"
	MessagePinned      DurableEventTypeV1 = "message.pinned"
	MessageUnpinned    DurableEventTypeV1 = "message.unpinned"
	MessageUpdated     DurableEventTypeV1 = "message.updated"
	ReactionAdded      DurableEventTypeV1 = "reaction.added"
	ReactionRemoved    DurableEventTypeV1 = "reaction.removed"
	ReadMarked         DurableEventTypeV1 = "read.marked"
	ThreadFollowed     DurableEventTypeV1 = "thread.followed"
	ThreadUnfollowed   DurableEventTypeV1 = "thread.unfollowed"
)

// Valid indicates whether the value is a known member of the DurableEventTypeV1 enum.
func (e DurableEventTypeV1) Valid() bool {
	switch e {
	case ActorStatusUpdated:
		return true
	case ChatArchived:
		return true
	case ChatCreated:
		return true
	case ChatUpdated:
		return true
	case DraftDeleted:
		return true
	case DraftUpdated:
		return true
	case MemberJoined:
		return true
	case MemberRemoved:
		return true
	case MemberUpdated:
		return true
	case MessageCreated:
		return true
	case MessageDeleted:
		return true
	case MessagePinned:
		return true
	case MessageUnpinned:
		return true
	case MessageUpdated:
		return true
	case ReactionAdded:
		return true
	case ReactionRemoved:
		return true
	case ReadMarked:
		return true
	case ThreadFollowed:
		return true
	case ThreadUnfollowed:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAlreadyBootstrapped    ErrorCode = "already_bootstrapped"
	ErrorCodeChatConflict           ErrorCode = "chat_conflict"
	ErrorCodeChatNotFound           ErrorCode = "chat_not_found"
	ErrorCodeEmailTaken             ErrorCode = "email_taken"
	ErrorCodeForbidden              ErrorCode = "forbidden"
	ErrorCodeIdempotencyConflict    ErrorCode = "idempotency_conflict"
	ErrorCodeInternalError          ErrorCode = "internal_error"
	ErrorCodeInvalidCredentials     ErrorCode = "invalid_credentials"
	ErrorCodeInvalidRefreshToken    ErrorCode = "invalid_refresh_token"
	ErrorCodeInvalidRequest         ErrorCode = "invalid_request"
	ErrorCodeInvitationInvalid      ErrorCode = "invitation_invalid"
	ErrorCodeMessageNotFound        ErrorCode = "message_not_found"
	ErrorCodeOriginNotAllowed       ErrorCode = "origin_not_allowed"
	ErrorCodePasswordChangeRequired ErrorCode = "password_change_required"
	ErrorCodePayloadTooLarge        ErrorCode = "payload_too_large"
	ErrorCodeRateLimited            ErrorCode = "rate_limited"
	ErrorCodeReauthenticationFailed ErrorCode = "reauthentication_failed"
	ErrorCodeServiceNotReady        ErrorCode = "service_not_ready"
	ErrorCodeSessionNotFound        ErrorCode = "session_not_found"
	ErrorCodeSmtpNotConfigured      ErrorCode = "smtp_not_configured"
	ErrorCodeTokenInvalid           ErrorCode = "token_invalid"
	ErrorCodeUnauthorized           ErrorCode = "unauthorized"
	ErrorCodeUnsupportedFormat      ErrorCode = "unsupported_format"
	ErrorCodeValidationFailed       ErrorCode = "validation_failed"
	ErrorCodeVersionConflict        ErrorCode = "version_conflict"
	ErrorCodeWorkspaceNotFound      ErrorCode = "workspace_not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAlreadyBootstrapped:
		return true
	case ErrorCodeChatConflict:
		return true
	case ErrorCodeChatNotFound:
		return true
	case ErrorCodeEmailTaken:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeIdempotencyConflict:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidCredentials:
		return true
	case ErrorCodeInvalidRefreshToken:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeInvitationInvalid:
		return true
	case ErrorCodeMessageNotFound:
		return true
	case ErrorCodeOriginNotAllowed:
		return true
	case ErrorCodePasswordChangeRequired:
		return true
	case ErrorCodePayloadTooLarge:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeReauthenticationFailed:
		return true
	case ErrorCodeServiceNotReady:
		return true
	case ErrorCodeSessionNotFound:
		return true
	case ErrorCodeSmtpNotConfigured:
		return true
	case ErrorCodeTokenInvalid:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupportedFormat:
		return true
	case ErrorCodeValidationFailed:
		return true
	case ErrorCodeVersionConflict:
		return true
	case ErrorCodeWorkspaceNotFound:
		return true
	default:
		return false
	}
}

// Defines values for InvitationRole.
const (
	InvitationRoleAdmin  InvitationRole = "admin"
	InvitationRoleMember InvitationRole = "member"
)

// Valid indicates whether the value is a known member of the InvitationRole enum.
func (e InvitationRole) Valid() bool {
	switch e {
	case InvitationRoleAdmin:
		return true
	case InvitationRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for MessageBodyFormat.
const (
	MessageBodyFormatMarkdown MessageBodyFormat = "markdown"
	MessageBodyFormatPlain    MessageBodyFormat = "plain"
)

// Valid indicates whether the value is a known member of the MessageBodyFormat enum.
func (e MessageBodyFormat) Valid() bool {
	switch e {
	case MessageBodyFormatMarkdown:
		return true
	case MessageBodyFormatPlain:
		return true
	default:
		return false
	}
}

// Defines values for MessageType.
const (
	Text MessageType = "text"
)

// Valid indicates whether the value is a known member of the MessageType enum.
func (e MessageType) Valid() bool {
	switch e {
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationMemberRole.
const (
	OrganizationMemberRoleAdmin  OrganizationMemberRole = "admin"
	OrganizationMemberRoleMember OrganizationMemberRole = "member"
	OrganizationMemberRoleOwner  OrganizationMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the OrganizationMemberRole enum.
func (e OrganizationMemberRole) Valid() bool {
	switch e {
	case OrganizationMemberRoleAdmin:
		return true
	case OrganizationMemberRoleMember:
		return true
	case OrganizationMemberRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationMemberStatus.
const (
	OrganizationMemberStatusActive      OrganizationMemberStatus = "active"
	OrganizationMemberStatusDeactivated OrganizationMemberStatus = "deactivated"
)

// Valid indicates whether the value is a known member of the OrganizationMemberStatus enum.
func (e OrganizationMemberStatus) Valid() bool {
	switch e {
	case OrganizationMemberStatusActive:
		return true
	case OrganizationMemberStatusDeactivated:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationSettingsInvitationDefaultRole.
const (
	OrganizationSettingsInvitationDefaultRoleAdmin  OrganizationSettingsInvitationDefaultRole = "admin"
	OrganizationSettingsInvitationDefaultRoleMember OrganizationSettingsInvitationDefaultRole = "member"
)

// Valid indicates whether the value is a known member of the OrganizationSettingsInvitationDefaultRole enum.
func (e OrganizationSettingsInvitationDefaultRole) Valid() bool {
	switch e {
	case OrganizationSettingsInvitationDefaultRoleAdmin:
		return true
	case OrganizationSettingsInvitationDefaultRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for Permission.
const (
	AuditRead          Permission = "audit.read"
	BrandingManage     Permission = "branding.manage"
	ChatsModerate      Permission = "chats.moderate"
	IntegrationsManage Permission = "integrations.manage"
	InvitationsManage  Permission = "invitations.manage"
	MembersManage      Permission = "members.manage"
	WorkspacePolicies  Permission = "workspace.policies"
	WorkspaceSettings  Permission = "workspace.settings"
)

// Valid indicates whether the value is a known member of the Permission enum.
func (e Permission) Valid() bool {
	switch e {
	case AuditRead:
		return true
	case BrandingManage:
		return true
	case ChatsModerate:
		return true
	case IntegrationsManage:
		return true
	case InvitationsManage:
		return true
	case MembersManage:
		return true
	case WorkspacePolicies:
		return true
	case WorkspaceSettings:
		return true
	default:
		return false
	}
}

// Defines values for PutDraftRequestBodyFormat.
const (
	PutDraftRequestBodyFormatMarkdown PutDraftRequestBodyFormat = "markdown"
	PutDraftRequestBodyFormatPlain    PutDraftRequestBodyFormat = "plain"
)

// Valid indicates whether the value is a known member of the PutDraftRequestBodyFormat enum.
func (e PutDraftRequestBodyFormat) Valid() bool {
	switch e {
	case PutDraftRequestBodyFormatMarkdown:
		return true
	case PutDraftRequestBodyFormatPlain:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeAckFrameV1Op.
const (
	Ack RealtimeAckFrameV1Op = "ack"
)

// Valid indicates whether the value is a known member of the RealtimeAckFrameV1Op enum.
func (e RealtimeAckFrameV1Op) Valid() bool {
	switch e {
	case Ack:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeAuthFrameV1Op.
const (
	Auth RealtimeAuthFrameV1Op = "auth"
)

// Valid indicates whether the value is a known member of the RealtimeAuthFrameV1Op enum.
func (e RealtimeAuthFrameV1Op) Valid() bool {
	switch e {
	case Auth:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeCloseCodeV1.
const (
	RealtimeCloseCodeV1AuthenticationFailed RealtimeCloseCodeV1 = 4001
	RealtimeCloseCodeV1NormalClosure        RealtimeCloseCodeV1 = 1000
	RealtimeCloseCodeV1PolicyViolation      RealtimeCloseCodeV1 = 1008
	RealtimeCloseCodeV1ResyncRequired       RealtimeCloseCodeV1 = 4009
	RealtimeCloseCodeV1ServiceRestart       RealtimeCloseCodeV1 = 1012
	RealtimeCloseCodeV1SlowConsumer         RealtimeCloseCodeV1 = 4008
)

// Valid indicates whether the value is a known member of the RealtimeCloseCodeV1 enum.
func (e RealtimeCloseCodeV1) Valid() bool {
	switch e {
	case RealtimeCloseCodeV1AuthenticationFailed:
		return true
	case RealtimeCloseCodeV1NormalClosure:
		return true
	case RealtimeCloseCodeV1PolicyViolation:
		return true
	case RealtimeCloseCodeV1ResyncRequired:
		return true
	case RealtimeCloseCodeV1ServiceRestart:
		return true
	case RealtimeCloseCodeV1SlowConsumer:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeDurableEventFrameV1Op.
const (
	Event RealtimeDurableEventFrameV1Op = "event"
)

// Valid indicates whether the value is a known member of the RealtimeDurableEventFrameV1Op enum.
func (e RealtimeDurableEventFrameV1Op) Valid() bool {
	switch e {
	case Event:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeHelloFrameV1Op.
const (
	Hello RealtimeHelloFrameV1Op = "hello"
)

// Valid indicates whether the value is a known member of the RealtimeHelloFrameV1Op enum.
func (e RealtimeHelloFrameV1Op) Valid() bool {
	switch e {
	case Hello:
		return true
	default:
		return false
	}
}

// Defines values for RealtimePresenceEventFrameV1Op.
const (
	RealtimePresenceEventFrameV1OpPresence RealtimePresenceEventFrameV1Op = "presence"
)

// Valid indicates whether the value is a known member of the RealtimePresenceEventFrameV1Op enum.
func (e RealtimePresenceEventFrameV1Op) Valid() bool {
	switch e {
	case RealtimePresenceEventFrameV1OpPresence:
		return true
	default:
		return false
	}
}

// Defines values for RealtimePresenceEventFrameV1State.
const (
	RealtimePresenceEventFrameV1StateAway    RealtimePresenceEventFrameV1State = "away"
	RealtimePresenceEventFrameV1StateOffline RealtimePresenceEventFrameV1State = "offline"
	RealtimePresenceEventFrameV1StateOnline  RealtimePresenceEventFrameV1State = "online"
)

// Valid indicates whether the value is a known member of the RealtimePresenceEventFrameV1State enum.
func (e RealtimePresenceEventFrameV1State) Valid() bool {
	switch e {
	case RealtimePresenceEventFrameV1StateAway:
		return true
	case RealtimePresenceEventFrameV1StateOffline:
		return true
	case RealtimePresenceEventFrameV1StateOnline:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeProtocolErrorFrameV1Code.
const (
	RealtimeProtocolErrorFrameV1CodeForbidden          RealtimeProtocolErrorFrameV1Code = "forbidden"
	RealtimeProtocolErrorFrameV1CodeInvalidFrame       RealtimeProtocolErrorFrameV1Code = "invalid_frame"
	RealtimeProtocolErrorFrameV1CodeNotAuthenticated   RealtimeProtocolErrorFrameV1Code = "not_authenticated"
	RealtimeProtocolErrorFrameV1CodeRateLimited        RealtimeProtocolErrorFrameV1Code = "rate_limited"
	RealtimeProtocolErrorFrameV1CodeServiceUnavailable RealtimeProtocolErrorFrameV1Code = "service_unavailable"
)

// Valid indicates whether the value is a known member of the RealtimeProtocolErrorFrameV1Code enum.
func (e RealtimeProtocolErrorFrameV1Code) Valid() bool {
	switch e {
	case RealtimeProtocolErrorFrameV1CodeForbidden:
		return true
	case RealtimeProtocolErrorFrameV1CodeInvalidFrame:
		return true
	case RealtimeProtocolErrorFrameV1CodeNotAuthenticated:
		return true
	case RealtimeProtocolErrorFrameV1CodeRateLimited:
		return true
	case RealtimeProtocolErrorFrameV1CodeServiceUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeProtocolErrorFrameV1Op.
const (
	RealtimeProtocolErrorFrameV1OpError RealtimeProtocolErrorFrameV1Op = "error"
)

// Valid indicates whether the value is a known member of the RealtimeProtocolErrorFrameV1Op enum.
func (e RealtimeProtocolErrorFrameV1Op) Valid() bool {
	switch e {
	case RealtimeProtocolErrorFrameV1OpError:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeResyncRequiredFrameV1Op.
const (
	RealtimeResyncRequiredFrameV1OpResyncRequired RealtimeResyncRequiredFrameV1Op = "resync_required"
)

// Valid indicates whether the value is a known member of the RealtimeResyncRequiredFrameV1Op enum.
func (e RealtimeResyncRequiredFrameV1Op) Valid() bool {
	switch e {
	case RealtimeResyncRequiredFrameV1OpResyncRequired:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeResyncRequiredFrameV1Reason.
const (
	EventHistoryExpired RealtimeResyncRequiredFrameV1Reason = "event_history_expired"
)

// Valid indicates whether the value is a known member of the RealtimeResyncRequiredFrameV1Reason enum.
func (e RealtimeResyncRequiredFrameV1Reason) Valid() bool {
	switch e {
	case EventHistoryExpired:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeSetPresenceFrameV1Op.
const (
	RealtimeSetPresenceFrameV1OpPresence RealtimeSetPresenceFrameV1Op = "presence"
)

// Valid indicates whether the value is a known member of the RealtimeSetPresenceFrameV1Op enum.
func (e RealtimeSetPresenceFrameV1Op) Valid() bool {
	switch e {
	case RealtimeSetPresenceFrameV1OpPresence:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeSetPresenceFrameV1State.
const (
	RealtimeSetPresenceFrameV1StateActive RealtimeSetPresenceFrameV1State = "active"
	RealtimeSetPresenceFrameV1StateAway   RealtimeSetPresenceFrameV1State = "away"
)

// Valid indicates whether the value is a known member of the RealtimeSetPresenceFrameV1State enum.
func (e RealtimeSetPresenceFrameV1State) Valid() bool {
	switch e {
	case RealtimeSetPresenceFrameV1StateActive:
		return true
	case RealtimeSetPresenceFrameV1StateAway:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeSubscribeActiveFrameV1Op.
const (
	SubscribeActive RealtimeSubscribeActiveFrameV1Op = "subscribe_active"
)

// Valid indicates whether the value is a known member of the RealtimeSubscribeActiveFrameV1Op enum.
func (e RealtimeSubscribeActiveFrameV1Op) Valid() bool {
	switch e {
	case SubscribeActive:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeTypingEventFrameV1Op.
const (
	RealtimeTypingEventFrameV1OpTyping RealtimeTypingEventFrameV1Op = "typing"
)

// Valid indicates whether the value is a known member of the RealtimeTypingEventFrameV1Op enum.
func (e RealtimeTypingEventFrameV1Op) Valid() bool {
	switch e {
	case RealtimeTypingEventFrameV1OpTyping:
		return true
	default:
		return false
	}
}

// Defines values for RealtimeTypingFrameV1Op.
const (
	RealtimeTypingFrameV1OpTyping RealtimeTypingFrameV1Op = "typing"
)

// Valid indicates whether the value is a known member of the RealtimeTypingFrameV1Op enum.
func (e RealtimeTypingFrameV1Op) Valid() bool {
	switch e {
	case RealtimeTypingFrameV1OpTyping:
		return true
	default:
		return false
	}
}

// Defines values for SMTPConfigurationSecurity.
const (
	SMTPConfigurationSecurityNone     SMTPConfigurationSecurity = "none"
	SMTPConfigurationSecurityStarttls SMTPConfigurationSecurity = "starttls"
	SMTPConfigurationSecurityTls      SMTPConfigurationSecurity = "tls"
)

// Valid indicates whether the value is a known member of the SMTPConfigurationSecurity enum.
func (e SMTPConfigurationSecurity) Valid() bool {
	switch e {
	case SMTPConfigurationSecurityNone:
		return true
	case SMTPConfigurationSecurityStarttls:
		return true
	case SMTPConfigurationSecurityTls:
		return true
	default:
		return false
	}
}

// Defines values for SMTPConfigurationUpdateSecurity.
const (
	SMTPConfigurationUpdateSecurityNone     SMTPConfigurationUpdateSecurity = "none"
	SMTPConfigurationUpdateSecurityStarttls SMTPConfigurationUpdateSecurity = "starttls"
	SMTPConfigurationUpdateSecurityTls      SMTPConfigurationUpdateSecurity = "tls"
)

// Valid indicates whether the value is a known member of the SMTPConfigurationUpdateSecurity enum.
func (e SMTPConfigurationUpdateSecurity) Valid() bool {
	switch e {
	case SMTPConfigurationUpdateSecurityNone:
		return true
	case SMTPConfigurationUpdateSecurityStarttls:
		return true
	case SMTPConfigurationUpdateSecurityTls:
		return true
	default:
		return false
	}
}

// Defines values for UpdateChatMemberRequestRole.
const (
	UpdateChatMemberRequestRoleAdmin  UpdateChatMemberRequestRole = "admin"
	UpdateChatMemberRequestRoleMember UpdateChatMemberRequestRole = "member"
	UpdateChatMemberRequestRoleOwner  UpdateChatMemberRequestRole = "owner"
)

// Valid indicates whether the value is a known member of the UpdateChatMemberRequestRole enum.
func (e UpdateChatMemberRequestRole) Valid() bool {
	switch e {
	case UpdateChatMemberRequestRoleAdmin:
		return true
	case UpdateChatMemberRequestRoleMember:
		return true
	case UpdateChatMemberRequestRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UpdateChatRequestVisibility.
const (
	UpdateChatRequestVisibilityPrivate UpdateChatRequestVisibility = "private"
	UpdateChatRequestVisibilityPublic  UpdateChatRequestVisibility = "public"
)

// Valid indicates whether the value is a known member of the UpdateChatRequestVisibility enum.
func (e UpdateChatRequestVisibility) Valid() bool {
	switch e {
	case UpdateChatRequestVisibilityPrivate:
		return true
	case UpdateChatRequestVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMessageRequestBodyFormat.
const (
	UpdateMessageRequestBodyFormatMarkdown UpdateMessageRequestBodyFormat = "markdown"
	UpdateMessageRequestBodyFormatPlain    UpdateMessageRequestBodyFormat = "plain"
)

// Valid indicates whether the value is a known member of the UpdateMessageRequestBodyFormat enum.
func (e UpdateMessageRequestBodyFormat) Valid() bool {
	switch e {
	case UpdateMessageRequestBodyFormatMarkdown:
		return true
	case UpdateMessageRequestBodyFormatPlain:
		return true
	default:
		return false
	}
}

// Defines values for UpdateOrganizationMemberRequestRole.
const (
	UpdateOrganizationMemberRequestRoleAdmin       UpdateOrganizationMemberRequestRole = "admin"
	UpdateOrganizationMemberRequestRoleLessThannil UpdateOrganizationMemberRequestRole = "<nil>"
	UpdateOrganizationMemberRequestRoleMember      UpdateOrganizationMemberRequestRole = "member"
)

// Valid indicates whether the value is a known member of the UpdateOrganizationMemberRequestRole enum.
func (e UpdateOrganizationMemberRequestRole) Valid() bool {
	switch e {
	case UpdateOrganizationMemberRequestRoleAdmin:
		return true
	case UpdateOrganizationMemberRequestRoleLessThannil:
		return true
	case UpdateOrganizationMemberRequestRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for UpdateOrganizationMemberRequestStatus.
const (
	UpdateOrganizationMemberRequestStatusActive      UpdateOrganizationMemberRequestStatus = "active"
	UpdateOrganizationMemberRequestStatusDeactivated UpdateOrganizationMemberRequestStatus = "deactivated"
	UpdateOrganizationMemberRequestStatusLessThannil UpdateOrganizationMemberRequestStatus = "<nil>"
)

// Valid indicates whether the value is a known member of the UpdateOrganizationMemberRequestStatus enum.
func (e UpdateOrganizationMemberRequestStatus) Valid() bool {
	switch e {
	case UpdateOrganizationMemberRequestStatusActive:
		return true
	case UpdateOrganizationMemberRequestStatusDeactivated:
		return true
	case UpdateOrganizationMemberRequestStatusLessThannil:
		return true
	default:
		return false
	}
}

// Defines values for UpdateOrganizationSettingsRequestInvitationDefaultRole.
const (
	UpdateOrganizationSettingsRequestInvitationDefaultRoleAdmin  UpdateOrganizationSettingsRequestInvitationDefaultRole = "admin"
	UpdateOrganizationSettingsRequestInvitationDefaultRoleMember UpdateOrganizationSettingsRequestInvitationDefaultRole = "member"
)

// Valid indicates whether the value is a known member of the UpdateOrganizationSettingsRequestInvitationDefaultRole enum.
func (e UpdateOrganizationSettingsRequestInvitationDefaultRole) Valid() bool {
	switch e {
	case UpdateOrganizationSettingsRequestInvitationDefaultRoleAdmin:
		return true
	case UpdateOrganizationSettingsRequestInvitationDefaultRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleOwner  UserRole = "owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleMember:
		return true
	case UserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive      UserStatus = "active"
	UserStatusDeactivated UserStatus = "deactivated"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDeactivated:
		return true
	default:
		return false
	}
}

// Defines values for UserPreferencesLocale.
const (
	En UserPreferencesLocale = "en"
	Ru UserPreferencesLocale = "ru"
)

// Valid indicates whether the value is a known member of the UserPreferencesLocale enum.
func (e UserPreferencesLocale) Valid() bool {
	switch e {
	case En:
		return true
	case Ru:
		return true
	default:
		return false
	}
}

// Defines values for UserPreferencesTheme.
const (
	Dark   UserPreferencesTheme = "dark"
	Light  UserPreferencesTheme = "light"
	System UserPreferencesTheme = "system"
)

// Valid indicates whether the value is a known member of the UserPreferencesTheme enum.
func (e UserPreferencesTheme) Valid() bool {
	switch e {
	case Dark:
		return true
	case Light:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for GetBrandingAssetParamsKind.
const (
	GetBrandingAssetParamsKindFavicon GetBrandingAssetParamsKind = "favicon"
	GetBrandingAssetParamsKindLogo    GetBrandingAssetParamsKind = "logo"
)

// Valid indicates whether the value is a known member of the GetBrandingAssetParamsKind enum.
func (e GetBrandingAssetParamsKind) Valid() bool {
	switch e {
	case GetBrandingAssetParamsKindFavicon:
		return true
	case GetBrandingAssetParamsKindLogo:
		return true
	default:
		return false
	}
}

// Defines values for DeleteBrandingAssetParamsKind.
const (
	DeleteBrandingAssetParamsKindFavicon DeleteBrandingAssetParamsKind = "favicon"
	DeleteBrandingAssetParamsKindLogo    DeleteBrandingAssetParamsKind = "logo"
)

// Valid indicates whether the value is a known member of the DeleteBrandingAssetParamsKind enum.
func (e DeleteBrandingAssetParamsKind) Valid() bool {
	switch e {
	case DeleteBrandingAssetParamsKindFavicon:
		return true
	case DeleteBrandingAssetParamsKindLogo:
		return true
	default:
		return false
	}
}

// Defines values for PutBrandingAssetParamsKind.
const (
	PutBrandingAssetParamsKindFavicon PutBrandingAssetParamsKind = "favicon"
	PutBrandingAssetParamsKindLogo    PutBrandingAssetParamsKind = "logo"
)

// Valid indicates whether the value is a known member of the PutBrandingAssetParamsKind enum.
func (e PutBrandingAssetParamsKind) Valid() bool {
	switch e {
	case PutBrandingAssetParamsKindFavicon:
		return true
	case PutBrandingAssetParamsKindLogo:
		return true
	default:
		return false
	}
}

// AcceptInvitationRequest defines model for AcceptInvitationRequest.
type AcceptInvitationRequest struct {
	DisplayName string  `json:"display_name"`
	Handle      string  `json:"handle"`
	Password    string  `json:"password"`
	Timezone    *string `json:"timezone,omitempty"`
}

// ActorPage defines model for ActorPage.
type ActorPage struct {
	Actors      []ActorSummary      `json:"actors"`
	NextAfterId *openapi_types.UUID `json:"next_after_id"`
}

// ActorSummary defines model for ActorSummary.
type ActorSummary struct {
	About           string             `json:"about"`
	ActorId         openapi_types.UUID `json:"actor_id"`
	DisplayName     string             `json:"display_name"`
	Handle          string             `json:"handle"`
	StatusEmoji     string             `json:"status_emoji"`
	StatusExpiresAt *time.Time         `json:"status_expires_at"`
	StatusText      string             `json:"status_text"`
	Title           string             `json:"title"`
	Type            ActorSummaryType   `json:"type"`
}

// ActorSummaryType defines model for ActorSummary.Type.
type ActorSummaryType string

// AddChatMemberRequest defines model for AddChatMemberRequest.
type AddChatMemberRequest struct {
	ActorId openapi_types.UUID        `json:"actor_id"`
	Role    *AddChatMemberRequestRole `json:"role,omitempty"`
}

// AddChatMemberRequestRole defines model for AddChatMemberRequest.Role.
type AddChatMemberRequestRole string

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action     string                 `json:"action"`
	ActorId    *openapi_types.UUID    `json:"actor_id"`
	ActorName  *string                `json:"actor_name"`
	CreatedAt  time.Time              `json:"created_at"`
	Id         openapi_types.UUID     `json:"id"`
	Metadata   map[string]interface{} `json:"metadata"`
	TargetId   *string                `json:"target_id"`
	TargetType string                 `json:"target_type"`
}

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Events []AuditEntry `json:"events"`
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	DisplayName      string              `json:"display_name"`
	Email            openapi_types.Email `json:"email"`
	Handle           string              `json:"handle"`
	OrganizationName string              `json:"organization_name"`
	OrganizationSlug string              `json:"organization_slug"`
	Password         string              `json:"password"`
	Timezone         *string             `json:"timezone,omitempty"`
}

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	Bootstrapped bool `json:"bootstrapped"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	CurrentPassword string              `json:"current_password"`
	NewEmail        openapi_types.Email `json:"new_email"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Chat defines model for Chat.
type Chat struct {
	ArchivedAt      *time.Time         `json:"archived_at,omitempty"`
	AvatarSeed      string             `json:"avatar_seed"`
	CreatedAt       time.Time          `json:"created_at"`
	DirectPeer      *ActorSummary      `json:"direct_peer,omitempty"`
	DisplayName     string             `json:"display_name"`
	Id              openapi_types.UUID `json:"id"`
	Kind            ChatKind           `json:"kind"`
	LastActivitySeq int64              `json:"last_activity_seq"`
	LastMessage     *MessagePreview    `json:"last_message,omitempty"`
	LastMessageAt   *time.Time         `json:"last_message_at,omitempty"`
	MutedUntil      *time.Time         `json:"muted_until"`
	Name            *string            `json:"name,omitempty"`
	NotifyLevel     ChatNotifyLevel    `json:"notify_level"`
	Role            ChatRole           `json:"role"`
	Topic           string             `json:"topic"`
	Visibility      ChatVisibility     `json:"visibility"`
}

// ChatKind defines model for Chat.Kind.
type ChatKind string

// ChatNotifyLevel defines model for Chat.NotifyLevel.
type ChatNotifyLevel string

// ChatRole defines model for Chat.Role.
type ChatRole string

// ChatVisibility defines model for Chat.Visibility.
type ChatVisibility string

// ChatFolder defines model for ChatFolder.
type ChatFolder struct {
	ChatIds []openapi_types.UUID `json:"chat_ids"`
	Color   ChatFolderColor      `json:"color"`
	Icon    ChatFolderIcon       `json:"icon"`
	Id      openapi_types.UUID   `json:"id"`
	Name    string               `json:"name"`
}

// ChatFolderColor defines model for ChatFolder.Color.
type ChatFolderColor string

// ChatFolderIcon defines model for ChatFolder.Icon.
type ChatFolderIcon string

// ChatMember defines model for ChatMember.
type ChatMember struct {
	ActorId         openapi_types.UUID `json:"actor_id"`
	DisplayName     string             `json:"display_name"`
	Handle          string             `json:"handle"`
	JoinedAt        time.Time          `json:"joined_at"`
	Role            ChatMemberRole     `json:"role"`
	StatusEmoji     string             `json:"status_emoji"`
	StatusExpiresAt *time.Time         `json:"status_expires_at"`
	StatusText      string             `json:"status_text"`
	Title           string             `json:"title"`
}

// ChatMemberRole defines model for ChatMember.Role.
type ChatMemberRole string

// ChatNotificationPreferences defines model for ChatNotificationPreferences.
type ChatNotificationPreferences struct {
	MutedUntil  *time.Time                             `json:"muted_until,omitempty"`
	NotifyLevel ChatNotificationPreferencesNotifyLevel `json:"notify_level"`
}

// ChatNotificationPreferencesNotifyLevel defines model for ChatNotificationPreferences.NotifyLevel.
type ChatNotificationPreferencesNotifyLevel string

// ChatUnread defines model for ChatUnread.
type ChatUnread struct {
	ChatId       openapi_types.UUID `json:"chat_id"`
	LastReadSeq  int64              `json:"last_read_seq"`
	MentionCount int64              `json:"mention_count"`
	UnreadCount  int64              `json:"unread_count"`
}

// ConfirmEmailRequest defines model for ConfirmEmailRequest.
type ConfirmEmailRequest struct {
	Token string `json:"token"`
}

// ConnectionTestRequest defines model for ConnectionTestRequest.
type ConnectionTestRequest struct {
	Kind ConnectionTestRequestKind `json:"kind"`
}

// ConnectionTestRequestKind defines model for ConnectionTestRequest.Kind.
type ConnectionTestRequestKind string

// ConnectionTestResult defines model for ConnectionTestResult.
type ConnectionTestResult struct {
	CheckedAt time.Time `json:"checked_at"`
	Message   string    `json:"message"`
	Ok        bool      `json:"ok"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Kind       CreateChatRequestKind        `json:"kind"`
	MemberIds  *[]openapi_types.UUID        `json:"member_ids,omitempty"`
	Name       *string                      `json:"name,omitempty"`
	Topic      *string                      `json:"topic,omitempty"`
	Visibility *CreateChatRequestVisibility `json:"visibility,omitempty"`
}

// CreateChatRequestKind defines model for CreateChatRequest.Kind.
type CreateChatRequestKind string

// CreateChatRequestVisibility defines model for CreateChatRequest.Visibility.
type CreateChatRequestVisibility string

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	Email openapi_types.Email          `json:"email"`
	Role  *CreateInvitationRequestRole `json:"role,omitempty"`
}

// CreateInvitationRequestRole defines model for CreateInvitationRequest.Role.
type CreateInvitationRequestRole string

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	Body              string                          `json:"body"`
	BodyFormat        *CreateMessageRequestBodyFormat `json:"body_format,omitempty"`
	ClientMsgId       openapi_types.UUID              `json:"client_msg_id"`
	MentionedActorIds *[]openapi_types.UUID           `json:"mentioned_actor_ids,omitempty"`
	ReplyToId         *openapi_types.UUID             `json:"reply_to_id,omitempty"`
	ThreadRootId      *openapi_types.UUID             `json:"thread_root_id,omitempty"`
}

// CreateMessageRequestBodyFormat defines model for CreateMessageRequest.BodyFormat.
type CreateMessageRequestBodyFormat string

// CustomStatus defines model for CustomStatus.
type CustomStatus struct {
	Emoji     string     `json:"emoji"`
	ExpiresAt *time.Time `json:"expires_at"`
	Text      string     `json:"text"`
}

// DirectoryChat defines model for DirectoryChat.
type DirectoryChat struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Kind      DirectoryChatKind  `json:"kind"`
	Name      string             `json:"name"`
	Topic     string             `json:"topic"`
}

// DirectoryChatKind defines model for DirectoryChat.Kind.
type DirectoryChatKind string

// Draft defines model for Draft.
type Draft struct {
	Body         string              `json:"body"`
	BodyFormat   DraftBodyFormat     `json:"body_format"`
	ChatId       openapi_types.UUID  `json:"chat_id"`
	ThreadRootId *openapi_types.UUID `json:"thread_root_id,omitempty"`
	UpdatedAt    time.Time           `json:"updated_at"`
	Version      int                 `json:"version"`
}

// DraftBodyFormat defines model for Draft.BodyFormat.
type DraftBodyFormat string

// DraftList defines model for DraftList.
type DraftList struct {
	Drafts []Draft `json:"drafts"`
}

// DurableEventTypeV1 defines model for DurableEventTypeV1.
type DurableEventTypeV1 string

// EmailChangeResponse defines model for EmailChangeResponse.
type EmailChangeResponse struct {
	PendingConfirmation bool  `json:"pending_confirmation"`
	User                *User `json:"user"`
}

// Error defines model for Error.
type Error struct {
	Code      ErrorCode               `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"request_id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ForwardAttribution defines model for ForwardAttribution.
type ForwardAttribution struct {
	AuthorHandle string    `json:"author_handle"`
	AuthorName   string    `json:"author_name"`
	CreatedAt    time.Time `json:"created_at"`
}

// ForwardMessageRequest defines model for ForwardMessageRequest.
type ForwardMessageRequest struct {
	ChatId      openapi_types.UUID `json:"chat_id"`
	ClientMsgId openapi_types.UUID `json:"client_msg_id"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// InfrastructureSettings defines model for InfrastructureSettings.
type InfrastructureSettings struct {
	S3      S3Configuration   `json:"s3"`
	Smtp    SMTPConfiguration `json:"smtp"`
	Version int64             `json:"version"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	AcceptUrl *string             `json:"accept_url,omitempty"`
	Email     openapi_types.Email `json:"email"`
	ExpiresAt time.Time           `json:"expires_at"`
	Id        openapi_types.UUID  `json:"id"`
	Role      InvitationRole      `json:"role"`
}

// InvitationRole defines model for Invitation.Role.
type InvitationRole string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MarkReadRequest defines model for MarkReadRequest.
type MarkReadRequest struct {
	LastReadSeq int64 `json:"last_read_seq"`
}

// Message defines model for Message.
type Message struct {
	ActorId           openapi_types.UUID   `json:"actor_id"`
	Body              string               `json:"body"`
	BodyFormat        MessageBodyFormat    `json:"body_format"`
	ChatId            openapi_types.UUID   `json:"chat_id"`
	ClientMsgId       openapi_types.UUID   `json:"client_msg_id"`
	CreatedAt         time.Time            `json:"created_at"`
	CreatedSeq        int64                `json:"created_seq"`
	DeletedAt         *time.Time           `json:"deleted_at,omitempty"`
	EditedAt          *time.Time           `json:"edited_at,omitempty"`
	ForwardedFrom     *ForwardAttribution  `json:"forwarded_from,omitempty"`
	Id                openapi_types.UUID   `json:"id"`
	MentionedActorIds []openapi_types.UUID `json:"mentioned_actor_ids"`
	ReplyToId         *openapi_types.UUID  `json:"reply_to_id,omitempty"`

	// ThreadReplyCount Number of non-deleted replies when this message is a thread root.
	ThreadReplyCount int64               `json:"thread_reply_count"`
	ThreadRootId     *openapi_types.UUID `json:"thread_root_id,omitempty"`
	Type             MessageType         `json:"type"`
	Version          int                 `json:"version"`
}

// MessageBodyFormat defines model for Message.BodyFormat.
type MessageBodyFormat string

// MessageType defines model for Message.Type.
type MessageType string

// MessagePage defines model for MessagePage.
type MessagePage struct {
	Messages      []Message `json:"messages"`
	NextBeforeSeq *int64    `json:"next_before_seq"`
}

// MessagePin defines model for MessagePin.
type MessagePin struct {
	MessageId openapi_types.UUID `json:"message_id"`
	PinnedAt  time.Time          `json:"pinned_at"`
	PinnedBy  openapi_types.UUID `json:"pinned_by"`
}

// MessagePinList defines model for MessagePinList.
type MessagePinList struct {
	Pins []MessagePin `json:"pins"`
}

// MessagePreview defines model for MessagePreview.
type MessagePreview struct {
	ActorDisplayName string             `json:"actor_display_name"`
	ActorId          openapi_types.UUID `json:"actor_id"`
	Body             string             `json:"body"`
	CreatedAt        time.Time          `json:"created_at"`
	CreatedSeq       int64              `json:"created_seq"`
	Deleted          bool               `json:"deleted"`
	Id               openapi_types.UUID `json:"id"`
}

// MessageReceipt defines model for MessageReceipt.
type MessageReceipt struct {
	ActorId openapi_types.UUID `json:"actor_id"`
	ReadAt  time.Time          `json:"read_at"`
}

// MessageReceiptList defines model for MessageReceiptList.
type MessageReceiptList struct {
	Receipts []MessageReceipt `json:"receipts"`
}

// MessageWindow defines model for MessageWindow.
type MessageWindow struct {
	HasEarlier bool               `json:"has_earlier"`
	HasLater   bool               `json:"has_later"`
	Messages   []Message          `json:"messages"`
	TargetId   openapi_types.UUID `json:"target_id"`
}

// OrganizationMember defines model for OrganizationMember.
type OrganizationMember struct {
	ActorId         openapi_types.UUID       `json:"actor_id"`
	CreatedAt       time.Time                `json:"created_at"`
	DisplayName     string                   `json:"display_name"`
	Email           openapi_types.Email      `json:"email"`
	Handle          string                   `json:"handle"`
	LastSeenAt      *time.Time               `json:"last_seen_at"`
	Permissions     []Permission             `json:"permissions"`
	Role            OrganizationMemberRole   `json:"role"`
	Status          OrganizationMemberStatus `json:"status"`
	StatusEmoji     string                   `json:"status_emoji"`
	StatusExpiresAt *time.Time               `json:"status_expires_at"`
	StatusText      string                   `json:"status_text"`
	Title           string                   `json:"title"`
}

// OrganizationMemberRole defines model for OrganizationMember.Role.
type OrganizationMemberRole string

// OrganizationMemberStatus defines model for OrganizationMember.Status.
type OrganizationMemberStatus string

// OrganizationSettings defines model for OrganizationSettings.
type OrganizationSettings struct {
	AccentColor             string                                    `json:"accent_color"`
	AllowChannelCreation    bool                                      `json:"allow_channel_creation"`
	AllowPublicChatCreation bool                                      `json:"allow_public_chat_creation"`
	HasFavicon              bool                                      `json:"has_favicon"`
	HasLogo                 bool                                      `json:"has_logo"`
	Id                      openapi_types.UUID                        `json:"id"`
	InvitationDefaultRole   OrganizationSettingsInvitationDefaultRole `json:"invitation_default_role"`
	InvitationTtlHours      int                                       `json:"invitation_ttl_hours"`
	Name                    string                                    `json:"name"`
	Slug                    string                                    `json:"slug"`
	Version                 int64                                     `json:"version"`
}

// OrganizationSettingsInvitationDefaultRole defines model for OrganizationSettings.InvitationDefaultRole.
type OrganizationSettingsInvitationDefaultRole string

// Permission defines model for Permission.
type Permission string

// PublicBranding defines model for PublicBranding.
type PublicBranding struct {
	AccentColor               string  `json:"accent_color"`
	FaviconUrl                *string `json:"favicon_url,omitempty"`
	LogoUrl                   *string `json:"logo_url,omitempty"`
	PasswordRecoveryAvailable bool    `json:"password_recovery_available"`
	Version                   int64   `json:"version"`
	WorkspaceName             string  `json:"workspace_name"`
}

// PushConfig defines model for PushConfig.
type PushConfig struct {
	Enabled   bool   `json:"enabled"`
	PublicKey string `json:"public_key"`
}

// PushSubscription defines model for PushSubscription.
type PushSubscription struct {
	CreatedAt time.Time          `json:"created_at"`
	Endpoint  string             `json:"endpoint"`
	Id        openapi_types.UUID `json:"id"`
}

// PushSubscriptionRequest defines model for PushSubscriptionRequest.
type PushSubscriptionRequest struct {
	Endpoint string `json:"endpoint"`
	Keys     struct {
		Auth   string `json:"auth"`
		P256dh string `json:"p256dh"`
	} `json:"keys"`
}

// PutDraftRequest defines model for PutDraftRequest.
type PutDraftRequest struct {
	Body            string                     `json:"body"`
	BodyFormat      *PutDraftRequestBodyFormat `json:"body_format,omitempty"`
	ExpectedVersion int                        `json:"expected_version"`
	ThreadRootId    *openapi_types.UUID        `json:"thread_root_id,omitempty"`
}

// PutDraftRequestBodyFormat defines model for PutDraftRequest.BodyFormat.
type PutDraftRequestBodyFormat string

// Reaction defines model for Reaction.
type Reaction struct {
	ActorId   openapi_types.UUID `json:"actor_id"`
	CreatedAt time.Time          `json:"created_at"`
	Emoji     string             `json:"emoji"`
	MessageId openapi_types.UUID `json:"message_id"`
}

// ReactionList defines model for ReactionList.
type ReactionList struct {
	Reactions []Reaction `json:"reactions"`
}

// ReadMarker defines model for ReadMarker.
type ReadMarker struct {
	ChatId       openapi_types.UUID  `json:"chat_id"`
	LastReadAt   time.Time           `json:"last_read_at"`
	LastReadSeq  int64               `json:"last_read_seq"`
	ThreadRootId *openapi_types.UUID `json:"thread_root_id,omitempty"`
}

// RealtimeAckFrameV1 defines model for RealtimeAckFrameV1.
type RealtimeAckFrameV1 struct {
	Op  RealtimeAckFrameV1Op `json:"op"`
	Seq int64                `json:"seq"`
}

// RealtimeAckFrameV1Op defines model for RealtimeAckFrameV1.Op.
type RealtimeAckFrameV1Op string

// RealtimeAuthFrameV1 defines model for RealtimeAuthFrameV1.
type RealtimeAuthFrameV1 struct {
	AccessToken string                `json:"access_token"`
	LastSeq     int64                 `json:"last_seq"`
	Op          RealtimeAuthFrameV1Op `json:"op"`
	RequestId   openapi_types.UUID    `json:"request_id"`
}

// RealtimeAuthFrameV1Op defines model for RealtimeAuthFrameV1.Op.
type RealtimeAuthFrameV1Op string

// RealtimeCloseCodeV1 defines model for RealtimeCloseCodeV1.
type RealtimeCloseCodeV1 int32

// RealtimeDurableEventFrameV1 defines model for RealtimeDurableEventFrameV1.
type RealtimeDurableEventFrameV1 struct {
	ActorId    openapi_types.UUID            `json:"actor_id"`
	ChatId     *openapi_types.UUID           `json:"chat_id,omitempty"`
	Data       map[string]interface{}        `json:"data"`
	OccurredAt time.Time                     `json:"occurred_at"`
	Op         RealtimeDurableEventFrameV1Op `json:"op"`
	Seq        int64                         `json:"seq"`
	SubjectId  openapi_types.UUID            `json:"subject_id"`
	Type       string                        `json:"type"`
}

// RealtimeDurableEventFrameV1Op defines model for RealtimeDurableEventFrameV1.Op.
type RealtimeDurableEventFrameV1Op string

// RealtimeHelloFrameV1 defines model for RealtimeHelloFrameV1.
type RealtimeHelloFrameV1 struct {
	AckBatchSize        int                    `json:"ack_batch_size"`
	AckIntervalMs       int                    `json:"ack_interval_ms"`
	ConnectionId        openapi_types.UUID     `json:"connection_id"`
	CurrentSeq          int64                  `json:"current_seq"`
	HeartbeatIntervalMs int                    `json:"heartbeat_interval_ms"`
	MaxUnackedEvents    int                    `json:"max_unacked_events"`
	MinRetainedSeq      int64                  `json:"min_retained_seq"`
	Op                  RealtimeHelloFrameV1Op `json:"op"`
	RequestId           openapi_types.UUID     `json:"request_id"`
}

// RealtimeHelloFrameV1Op defines model for RealtimeHelloFrameV1.Op.
type RealtimeHelloFrameV1Op string

// RealtimePresenceEventFrameV1 defines model for RealtimePresenceEventFrameV1.
type RealtimePresenceEventFrameV1 struct {
	ActorId   openapi_types.UUID                `json:"actor_id"`
	ExpiresAt time.Time                         `json:"expires_at"`
	Op        RealtimePresenceEventFrameV1Op    `json:"op"`
	State     RealtimePresenceEventFrameV1State `json:"state"`
}

// RealtimePresenceEventFrameV1Op defines model for RealtimePresenceEventFrameV1.Op.
type RealtimePresenceEventFrameV1Op string

// RealtimePresenceEventFrameV1State defines model for RealtimePresenceEventFrameV1.State.
type RealtimePresenceEventFrameV1State string

// RealtimeProtocolErrorFrameV1 defines model for RealtimeProtocolErrorFrameV1.
type RealtimeProtocolErrorFrameV1 struct {
	Code      RealtimeProtocolErrorFrameV1Code `json:"code"`
	Message   string                           `json:"message"`
	Op        RealtimeProtocolErrorFrameV1Op   `json:"op"`
	RequestId *openapi_types.UUID              `json:"request_id,omitempty"`
}

// RealtimeProtocolErrorFrameV1Code defines model for RealtimeProtocolErrorFrameV1.Code.
type RealtimeProtocolErrorFrameV1Code string

// RealtimeProtocolErrorFrameV1Op defines model for RealtimeProtocolErrorFrameV1.Op.
type RealtimeProtocolErrorFrameV1Op string

// RealtimeResyncRequiredFrameV1 defines model for RealtimeResyncRequiredFrameV1.
type RealtimeResyncRequiredFrameV1 struct {
	CurrentSeq     int64                               `json:"current_seq"`
	MinRetainedSeq int64                               `json:"min_retained_seq"`
	Op             RealtimeResyncRequiredFrameV1Op     `json:"op"`
	Reason         RealtimeResyncRequiredFrameV1Reason `json:"reason"`
}

// RealtimeResyncRequiredFrameV1Op defines model for RealtimeResyncRequiredFrameV1.Op.
type RealtimeResyncRequiredFrameV1Op string

// RealtimeResyncRequiredFrameV1Reason defines model for RealtimeResyncRequiredFrameV1.Reason.
type RealtimeResyncRequiredFrameV1Reason string

// RealtimeSetPresenceFrameV1 defines model for RealtimeSetPresenceFrameV1.
type RealtimeSetPresenceFrameV1 struct {
	Op    RealtimeSetPresenceFrameV1Op    `json:"op"`
	State RealtimeSetPresenceFrameV1State `json:"state"`
}

// RealtimeSetPresenceFrameV1Op defines model for RealtimeSetPresenceFrameV1.Op.
type RealtimeSetPresenceFrameV1Op string

// RealtimeSetPresenceFrameV1State defines model for RealtimeSetPresenceFrameV1.State.
type RealtimeSetPresenceFrameV1State string

// RealtimeSubscribeActiveFrameV1 defines model for RealtimeSubscribeActiveFrameV1.
type RealtimeSubscribeActiveFrameV1 struct {
	ChatId       *openapi_types.UUID              `json:"chat_id"`
	Op           RealtimeSubscribeActiveFrameV1Op `json:"op"`
	ThreadRootId *openapi_types.UUID              `json:"thread_root_id"`
}

// RealtimeSubscribeActiveFrameV1Op defines model for RealtimeSubscribeActiveFrameV1.Op.
type RealtimeSubscribeActiveFrameV1Op string

// RealtimeTypingEventFrameV1 defines model for RealtimeTypingEventFrameV1.
type RealtimeTypingEventFrameV1 struct {
	Active       bool                         `json:"active"`
	ActorId      openapi_types.UUID           `json:"actor_id"`
	ChatId       openapi_types.UUID           `json:"chat_id"`
	ExpiresAt    time.Time                    `json:"expires_at"`
	Op           RealtimeTypingEventFrameV1Op `json:"op"`
	ThreadRootId *openapi_types.UUID          `json:"thread_root_id"`
}

// RealtimeTypingEventFrameV1Op defines model for RealtimeTypingEventFrameV1.Op.
type RealtimeTypingEventFrameV1Op string

// RealtimeTypingFrameV1 defines model for RealtimeTypingFrameV1.
type RealtimeTypingFrameV1 struct {
	Active       bool                    `json:"active"`
	ChatId       openapi_types.UUID      `json:"chat_id"`
	Op           RealtimeTypingFrameV1Op `json:"op"`
	ThreadRootId *openapi_types.UUID     `json:"thread_root_id"`
}

// RealtimeTypingFrameV1Op defines model for RealtimeTypingFrameV1.Op.
type RealtimeTypingFrameV1Op string

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// S3Configuration defines model for S3Configuration.
type S3Configuration struct {
	AccessKeyHint         *string `json:"access_key_hint,omitempty"`
	Bucket                string  `json:"bucket"`
	CredentialsConfigured bool    `json:"credentials_configured"`
	Endpoint              string  `json:"endpoint"`
	ForcePathStyle        bool    `json:"force_path_style"`
	Prefix                string  `json:"prefix"`
	Region                string  `json:"region"`
}

// S3ConfigurationUpdate defines model for S3ConfigurationUpdate.
type S3ConfigurationUpdate struct {
	AccessKey        *string `json:"access_key,omitempty"`
	Bucket           string  `json:"bucket"`
	ClearCredentials bool    `json:"clear_credentials"`
	Endpoint         string  `json:"endpoint"`
	ForcePathStyle   bool    `json:"force_path_style"`
	Prefix           string  `json:"prefix"`
	Region           string  `json:"region"`
	SecretKey        *string `json:"secret_key,omitempty"`
}

// SMTPConfiguration defines model for SMTPConfiguration.
type SMTPConfiguration struct {
	CredentialsConfigured bool                      `json:"credentials_configured"`
	FromAddress           string                    `json:"from_address"`
	FromName              string                    `json:"from_name"`
	Host                  string                    `json:"host"`
	Port                  int                       `json:"port"`
	Security              SMTPConfigurationSecurity `json:"security"`
	Username              string                    `json:"username"`
}

// SMTPConfigurationSecurity defines model for SMTPConfiguration.Security.
type SMTPConfigurationSecurity string

// SMTPConfigurationUpdate defines model for SMTPConfigurationUpdate.
type SMTPConfigurationUpdate struct {
	ClearCredentials bool                            `json:"clear_credentials"`
	FromAddress      string                          `json:"from_address"`
	FromName         string                          `json:"from_name"`
	Host             string                          `json:"host"`
	Password         *string                         `json:"password,omitempty"`
	Port             int                             `json:"port"`
	Security         SMTPConfigurationUpdateSecurity `json:"security"`
	Username         string                          `json:"username"`
}

// SMTPConfigurationUpdateSecurity defines model for SMTPConfigurationUpdate.Security.
type SMTPConfigurationUpdateSecurity string

// Session defines model for Session.
type Session struct {
	CreatedAt  time.Time          `json:"created_at"`
	Current    bool               `json:"current"`
	ExpiresAt  time.Time          `json:"expires_at"`
	Id         openapi_types.UUID `json:"id"`
	IpAddress  *string            `json:"ip_address,omitempty"`
	LastSeenAt time.Time          `json:"last_seen_at"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
	UserAgent  string             `json:"user_agent"`
}

// SetStatusRequest defines model for SetStatusRequest.
type SetStatusRequest struct {
	Emoji     string     `json:"emoji"`
	ExpiresAt *time.Time `json:"expires_at"`
	Text      string     `json:"text"`
}

// ThreadFollow defines model for ThreadFollow.
type ThreadFollow struct {
	FollowedAt   time.Time          `json:"followed_at"`
	ThreadRootId openapi_types.UUID `json:"thread_root_id"`
}

// ThreadPage defines model for ThreadPage.
type ThreadPage struct {
	NextBeforeSeq *int64          `json:"next_before_seq"`
	Threads       []ThreadSummary `json:"threads"`
}

// ThreadSummary defines model for ThreadSummary.
type ThreadSummary struct {
	FollowedAt      time.Time `json:"followed_at"`
	LastActivitySeq int64     `json:"last_activity_seq"`
	LastReplySeq    *int64    `json:"last_reply_seq,omitempty"`
	ReplyCount      int64     `json:"reply_count"`
	Root            Message   `json:"root"`
}

// ThreadUnread defines model for ThreadUnread.
type ThreadUnread struct {
	ChatId       openapi_types.UUID `json:"chat_id"`
	LastReadSeq  int64              `json:"last_read_seq"`
	MentionCount int64              `json:"mention_count"`
	ThreadRootId openapi_types.UUID `json:"thread_root_id"`
	UnreadCount  int64              `json:"unread_count"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessExpiresAt time.Time `json:"access_expires_at"`
	AccessToken     string    `json:"access_token"`
	User            User      `json:"user"`
}

// TransferOwnershipRequest defines model for TransferOwnershipRequest.
type TransferOwnershipRequest struct {
	CurrentPassword string             `json:"current_password"`
	TargetActorId   openapi_types.UUID `json:"target_actor_id"`
}

// UnreadSnapshot defines model for UnreadSnapshot.
type UnreadSnapshot struct {
	Chats   []ChatUnread   `json:"chats"`
	Threads []ThreadUnread `json:"threads"`
}

// UpdateChatMemberRequest defines model for UpdateChatMemberRequest.
type UpdateChatMemberRequest struct {
	Role UpdateChatMemberRequestRole `json:"role"`
}

// UpdateChatMemberRequestRole defines model for UpdateChatMemberRequest.Role.
type UpdateChatMemberRequestRole string

// UpdateChatRequest defines model for UpdateChatRequest.
type UpdateChatRequest struct {
	Name       *string                      `json:"name,omitempty"`
	Topic      *string                      `json:"topic,omitempty"`
	Visibility *UpdateChatRequestVisibility `json:"visibility,omitempty"`
}

// UpdateChatRequestVisibility defines model for UpdateChatRequest.Visibility.
type UpdateChatRequestVisibility string

// UpdateInfrastructureSettingsRequest defines model for UpdateInfrastructureSettingsRequest.
type UpdateInfrastructureSettingsRequest struct {
	ExpectedVersion int64                   `json:"expected_version"`
	S3              S3ConfigurationUpdate   `json:"s3"`
	Smtp            SMTPConfigurationUpdate `json:"smtp"`
}

// UpdateMessageRequest defines model for UpdateMessageRequest.
type UpdateMessageRequest struct {
	Body              string                          `json:"body"`
	BodyFormat        *UpdateMessageRequestBodyFormat `json:"body_format,omitempty"`
	ExpectedVersion   int                             `json:"expected_version"`
	MentionedActorIds *[]openapi_types.UUID           `json:"mentioned_actor_ids,omitempty"`
}

// UpdateMessageRequestBodyFormat defines model for UpdateMessageRequest.BodyFormat.
type UpdateMessageRequestBodyFormat string

// UpdateOrganizationMemberRequest defines model for UpdateOrganizationMemberRequest.
type UpdateOrganizationMemberRequest struct {
	Permissions *[]Permission                          `json:"permissions,omitempty"`
	Role        *UpdateOrganizationMemberRequestRole   `json:"role,omitempty"`
	Status      *UpdateOrganizationMemberRequestStatus `json:"status,omitempty"`
}

// UpdateOrganizationMemberRequestRole defines model for UpdateOrganizationMemberRequest.Role.
type UpdateOrganizationMemberRequestRole string

// UpdateOrganizationMemberRequestStatus defines model for UpdateOrganizationMemberRequest.Status.
type UpdateOrganizationMemberRequestStatus string

// UpdateOrganizationSettingsRequest defines model for UpdateOrganizationSettingsRequest.
type UpdateOrganizationSettingsRequest struct {
	AccentColor             string                                                 `json:"accent_color"`
	AllowChannelCreation    bool                                                   `json:"allow_channel_creation"`
	AllowPublicChatCreation bool                                                   `json:"allow_public_chat_creation"`
	ExpectedVersion         int64                                                  `json:"expected_version"`
	InvitationDefaultRole   UpdateOrganizationSettingsRequestInvitationDefaultRole `json:"invitation_default_role"`
	InvitationTtlHours      int                                                    `json:"invitation_ttl_hours"`
	Name                    string                                                 `json:"name"`
	Slug                    string                                                 `json:"slug"`
}

// UpdateOrganizationSettingsRequestInvitationDefaultRole defines model for UpdateOrganizationSettingsRequest.InvitationDefaultRole.
type UpdateOrganizationSettingsRequestInvitationDefaultRole string

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	About       *string `json:"about,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Handle      *string `json:"handle,omitempty"`
	Timezone    *string `json:"timezone,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	About              string              `json:"about"`
	CreatedAt          time.Time           `json:"created_at"`
	DisplayName        string              `json:"display_name"`
	Email              openapi_types.Email `json:"email"`
	Handle             string              `json:"handle"`
	Id                 openapi_types.UUID  `json:"id"`
	MustChangePassword bool                `json:"must_change_password"`
	OrgId              openapi_types.UUID  `json:"org_id"`
	OrganizationName   string              `json:"organization_name"`
	Permissions        []Permission        `json:"permissions"`
	Role               UserRole            `json:"role"`
	Status             UserStatus          `json:"status"`
	StatusEmoji        string              `json:"status_emoji"`
	StatusExpiresAt    *time.Time          `json:"status_expires_at"`
	StatusText         string              `json:"status_text"`
	Timezone           string              `json:"timezone"`
	Title              string              `json:"title"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserStatus defines model for User.Status.
type UserStatus string

// UserPreferences defines model for UserPreferences.
type UserPreferences struct {
	ChatFolders   []ChatFolder          `json:"chat_folders"`
	Locale        UserPreferencesLocale `json:"locale"`
	PinnedChatIds []openapi_types.UUID  `json:"pinned_chat_ids"`
	PushEnabled   bool                  `json:"push_enabled"`
	PushPreview   bool                  `json:"push_preview"`
	Theme         UserPreferencesTheme  `json:"theme"`
}

// UserPreferencesLocale defines model for UserPreferences.Locale.
type UserPreferencesLocale string

// UserPreferencesTheme defines model for UserPreferences.Theme.
type UserPreferencesTheme string

// ActorId defines model for ActorId.
type ActorId = openapi_types.UUID

// ChatId defines model for ChatId.
type ChatId = openapi_types.UUID

// MessageId defines model for MessageId.
type MessageId = openapi_types.UUID

// Tokens defines model for Tokens.
type Tokens = TokenResponse

// ListActorsParams defines parameters for ListActors.
type ListActorsParams struct {
	Q       *string             `form:"q,omitempty" json:"q,omitempty"`
	AfterId *openapi_types.UUID `form:"after_id,omitempty" json:"after_id,omitempty"`
	Limit   *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// BootstrapParams defines parameters for Bootstrap.
type BootstrapParams struct {
	// XComaBootstrapToken Required outside development; configure it with BOOTSTRAP_TOKEN.
	XComaBootstrapToken *string `json:"X-Coma-Bootstrap-Token,omitempty"`
}

// GetBrandingAssetParamsKind defines parameters for GetBrandingAsset.
type GetBrandingAssetParamsKind string

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	BeforeSeq    *int64              `form:"before_seq,omitempty" json:"before_seq,omitempty"`
	Limit        *int                `form:"limit,omitempty" json:"limit,omitempty"`
	ThreadRootId *openapi_types.UUID `form:"thread_root_id,omitempty" json:"thread_root_id,omitempty"`
}

// DeleteDraftParams defines parameters for DeleteDraft.
type DeleteDraftParams struct {
	ThreadRootId *openapi_types.UUID `form:"thread_root_id,omitempty" json:"thread_root_id,omitempty"`
}

// GetMessageContextParams defines parameters for GetMessageContext.
type GetMessageContextParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListThreadMessagesParams defines parameters for ListThreadMessages.
type ListThreadMessagesParams struct {
	BeforeSeq *int64 `form:"before_seq,omitempty" json:"before_seq,omitempty"`
	Limit     *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrganizationAuditParams defines parameters for ListOrganizationAudit.
type ListOrganizationAuditParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteBrandingAssetParamsKind defines parameters for DeleteBrandingAsset.
type DeleteBrandingAssetParamsKind string

// PutBrandingAssetParamsKind defines parameters for PutBrandingAsset.
type PutBrandingAssetParamsKind string

// ListFollowedThreadsParams defines parameters for ListFollowedThreads.
type ListFollowedThreadsParams struct {
	BeforeSeq *int64 `form:"before_seq,omitempty" json:"before_seq,omitempty"`
	Limit     *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// BootstrapJSONRequestBody defines body for Bootstrap for application/json ContentType.
type BootstrapJSONRequestBody = BootstrapRequest

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// UpdateChatJSONRequestBody defines body for UpdateChat for application/json ContentType.
type UpdateChatJSONRequestBody = UpdateChatRequest

// AddChatMemberJSONRequestBody defines body for AddChatMember for application/json ContentType.
type AddChatMemberJSONRequestBody = AddChatMemberRequest

// UpdateChatMemberJSONRequestBody defines body for UpdateChatMember for application/json ContentType.
type UpdateChatMemberJSONRequestBody = UpdateChatMemberRequest

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = CreateMessageRequest

// UpdateChatNotificationPreferencesJSONRequestBody defines body for UpdateChatNotificationPreferences for application/json ContentType.
type UpdateChatNotificationPreferencesJSONRequestBody = ChatNotificationPreferences

// MarkChatReadJSONRequestBody defines body for MarkChatRead for application/json ContentType.
type MarkChatReadJSONRequestBody = MarkReadRequest

// PutDraftJSONRequestBody defines body for PutDraft for application/json ContentType.
type PutDraftJSONRequestBody = PutDraftRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = CreateInvitationRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = AcceptInvitationRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ChangeEmailJSONRequestBody defines body for ChangeEmail for application/json ContentType.
type ChangeEmailJSONRequestBody = ChangeEmailRequest

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = ConfirmEmailRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// SetStatusJSONRequestBody defines body for SetStatus for application/json ContentType.
type SetStatusJSONRequestBody = SetStatusRequest

// UpdateMessageJSONRequestBody defines body for UpdateMessage for application/json ContentType.
type UpdateMessageJSONRequestBody = UpdateMessageRequest

// ForwardMessageJSONRequestBody defines body for ForwardMessage for application/json ContentType.
type ForwardMessageJSONRequestBody = ForwardMessageRequest

// MarkThreadReadJSONRequestBody defines body for MarkThreadRead for application/json ContentType.
type MarkThreadReadJSONRequestBody = MarkReadRequest

// UpdateOrganizationSettingsJSONRequestBody defines body for UpdateOrganizationSettings for application/json ContentType.
type UpdateOrganizationSettingsJSONRequestBody = UpdateOrganizationSettingsRequest

// UpdateInfrastructureSettingsJSONRequestBody defines body for UpdateInfrastructureSettings for application/json ContentType.
type UpdateInfrastructureSettingsJSONRequestBody = UpdateInfrastructureSettingsRequest

// TestInfrastructureConnectionJSONRequestBody defines body for TestInfrastructureConnection for application/json ContentType.
type TestInfrastructureConnectionJSONRequestBody = ConnectionTestRequest

// UpdateOrganizationMemberJSONRequestBody defines body for UpdateOrganizationMember for application/json ContentType.
type UpdateOrganizationMemberJSONRequestBody = UpdateOrganizationMemberRequest

// TransferOrganizationOwnershipJSONRequestBody defines body for TransferOrganizationOwnership for application/json ContentType.
type TransferOrganizationOwnershipJSONRequestBody = TransferOwnershipRequest

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody = UserPreferences

// PutPushSubscriptionJSONRequestBody defines body for PutPushSubscription for application/json ContentType.
type PutPushSubscriptionJSONRequestBody = PushSubscriptionRequest
