const { withAppBuildGradle } = require("expo/config-plugins");

// android/ is regenerated by `expo prebuild`, so release signing is appended
// to build.gradle by this plugin instead of being edited by hand. The upload
// keystore and its passwords stay outside the repository, in
// ~/.gradle/gradle.properties:
//   COMA_UPLOAD_STORE_FILE=/absolute/path/coma-upload.jks
//   COMA_UPLOAD_STORE_PASSWORD=...
//   COMA_UPLOAD_KEY_ALIAS=coma-upload
//   COMA_UPLOAD_KEY_PASSWORD=...
// Without them a release build keeps the debug signature, which Google Play
// rejects; the fastlane lane checks the properties before building.

const MARKER = "// coma: release signing (withAndroidReleaseSigning)";

const SIGNING_BLOCK = `
${MARKER}
def comaUploadStoreFile = project.findProperty('COMA_UPLOAD_STORE_FILE')
if (comaUploadStoreFile != null && !comaUploadStoreFile.toString().isEmpty()) {
    android {
        signingConfigs {
            create('comaUpload') {
                storeFile file(comaUploadStoreFile)
                storePassword project.findProperty('COMA_UPLOAD_STORE_PASSWORD')
                keyAlias project.findProperty('COMA_UPLOAD_KEY_ALIAS')
                keyPassword project.findProperty('COMA_UPLOAD_KEY_PASSWORD')
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.comaUpload
            }
        }
    }
} else {
    project.logger.warn('[coma] COMA_UPLOAD_STORE_FILE is not set: the release build keeps the debug signature.')
}
`;

module.exports = (config) =>
  withAppBuildGradle(config, (androidConfig) => {
    if (androidConfig.modResults.language !== "groovy")
      throw new Error(
        "[withAndroidReleaseSigning] expected a Groovy build.gradle",
      );
    if (!androidConfig.modResults.contents.includes(MARKER))
      androidConfig.modResults.contents += SIGNING_BLOCK;
    return androidConfig;
  });
